#!/usr/bin/env python3
"""
Generate docs/CHECKS.md from docs/checks.yaml plus a live run over the corpus.

    python3 tools/gen_checks.py            # write docs/CHECKS.md
    python3 tools/gen_checks.py --check    # fail if stale or undocumented — for CI

Two things it guarantees, both of which have already gone wrong here once:

1. **No undocumented check can ship.** If `tools/derive.py` emits a pattern with no entry in
   `checks.yaml`, this fails. A check whose message is its only documentation is a check
   nobody can act on.
2. **The example is real.** Each entry shows an actual finding from an actual spec in the
   corpus, produced by running the linter, not written by hand. Hand-written examples drift
   from the checker the moment the checker improves.
"""
import sys, os, re, io, json, glob, subprocess, collections

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
META = yaml.safe_load(open(os.path.join(ROOT, "docs", "checks.yaml")))

CORPUS = (sorted(glob.glob(os.path.join(ROOT, "examples", "**", "*.loop.yaml"), recursive=True))
          + sorted(glob.glob(os.path.join(ROOT, "research", "published_study",
                                          "encodings*", "*.loop.yaml"))))

EVIDENCE = {
    "robust":    ("**robust**", "survived independent encoding by a model that had never seen "
                                "this project"),
    "corpus":    ("measured", "fires on the corpus; not separately checked against an "
                              "independent encoder"),
    "motivated": ("motivated", "three real instances justify it; **not yet evidenced at rate**"),
    "legacy":    ("legacy", "inherited from the general programme, never fires on agent loops"),
}


def run_corpus():
    """One real finding per pattern, and how many specs each fires on."""
    example, count = {}, collections.Counter()
    for f in CORPUS:
        exp = subprocess.run(["python3", os.path.join(ROOT, "tools", "loop.py"), f],
                             capture_output=True, text=True)
        if exp.returncode:
            continue
        tmp = "/tmp/_gc.yaml"
        open(tmp, "w").write(exp.stdout)
        out = subprocess.run(["python3", os.path.join(ROOT, "tools", "derive.py"), tmp,
                              "--json"], capture_output=True, text=True).stdout
        try:
            claims = [c for cs in json.loads(out).values() for c in cs]
        except json.JSONDecodeError:
            continue
        seen = set()
        for c in claims:
            p = c["pattern"]
            seen.add(p)
            example.setdefault(p, (os.path.relpath(f, ROOT), c["claim"]))
        count.update(seen)
    return example, count


def emitted():
    return set(re.findall(r'"pattern": "(\w+)"',
                          open(os.path.join(ROOT, "tools", "derive.py")).read()))


def markdown(example, count):
    o = io.StringIO()
    o.write("# The checks\n\n")
    o.write("**Generated by `tools/gen_checks.py` from `docs/checks.yaml` and a live run over "
            f"{len(CORPUS)} specs. Do not edit.**\n\n")
    o.write("Every example below is a real finding from a real spec in this repo, produced by "
            "running the\nlinter — not written by hand.\n\n")
    o.write("**Evidence column, and read it before quoting any rate:**\n\n")
    for k, (label, desc) in EVIDENCE.items():
        o.write(f"- {label} — {desc}\n")
    o.write("\n> Only two checks are `robust`. Everything else measured the person doing the "
            "encoding\n> as much as it measured the corpus. That is the honest ceiling on "
            "current evidence, and\n> it is why this is a notation first and a linter second.\n\n")

    live = [(p, m) for p, m in META.items() if m.get("evidence") != "legacy"]
    live.sort(key=lambda x: (-count.get(x[0], 0), x[0]))

    o.write("| check | fires on | half | felt symptom |\n|---|---|---|---|\n")
    for p, m in live:
        half = {"attention": "attention", "calibration": "calibration"}.get(m.get("half"), "—")
        o.write(f"| [`{p}`](#{p.replace('_','-')}) | {count.get(p,0)}/{len(CORPUS)} | {half} "
                f"| *\"{m['symptom']}\"* |\n")
    o.write("\n---\n\n")

    for p, m in live:
        o.write(f"## `{p}`\n\n")
        o.write(f"> *\"{m['symptom']}\"*\n\n")
        o.write(f"**What it looked at.** {m['means']}\n\n")
        o.write(f"**How to fix it.** {m['fix']}\n\n")
        bits = [f"fires on **{count.get(p,0)} of {len(CORPUS)}** specs here",
                EVIDENCE[m.get('evidence','corpus')][0]]
        if m.get("half") in ("attention", "calibration"):
            bits.append(f"the *{m['half']}* half")
        o.write(f"**Status.** " + " · ".join(bits) + ".")
        if m.get("grounded"):
            o.write(f" {m['grounded']}")
        o.write("\n\n")
        if p in example:
            src, claim = example[p]
            o.write(f"**Real finding**, from `{src}`:\n\n> {claim}\n\n")
        o.write("---\n\n")

    legacy = [(p, m) for p, m in META.items() if m.get("evidence") == "legacy"]
    o.write("## Legacy checks\n\n")
    o.write("Inherited from the general programme, before the fork to agent loops. None fires "
            "on the\ncurrent corpus. Kept because they are still correct for hand-written "
            "graph encodings, and\nrecorded here so nobody mistakes silence for coverage.\n\n")
    o.write("| check | why it is quiet |\n|---|---|\n")
    for p, m in sorted(legacy):
        o.write(f"| `{p}` | {' '.join(str(m['means']).split())} |\n")
    return o.getvalue()


if __name__ == "__main__":
    undoc = emitted() - set(META)
    if undoc:
        sys.exit("UNDOCUMENTED CHECK(S) — add to docs/checks.yaml:\n" +
                 "\n".join(f"  {p}" for p in sorted(undoc)))
    stale_meta = set(META) - emitted()
    if stale_meta:
        print(f"note: documented but not emitted: {sorted(stale_meta)}", file=sys.stderr)

    ex, cnt = run_corpus()
    md = markdown(ex, cnt)
    path = os.path.join(ROOT, "docs", "CHECKS.md")
    if "--check" in sys.argv:
        if not os.path.exists(path) or open(path).read() != md:
            sys.exit("docs/CHECKS.md is stale — regenerate with tools/gen_checks.py")
        print("checks doc is current")
    else:
        open(path, "w").write(md)
        print(f"wrote docs/CHECKS.md — {len(META)} checks, {sum(cnt.values())} findings "
              f"across {len(CORPUS)} specs")
